name: appx
description: Various


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  social_login_buttons: ^1.0.6
  ionicons: ^0.1.2
  material_design_icons_flutter: ^5.0.6595
  google_sign_in: ^5.2.2
  firebase_auth: ^3.3.5
  sqflite: ^2.0.1
  path_provider: ^2.0.8
  http: ^0.13.4
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  json_annotation: ^4.4.0
  graphql: ^5.0.0
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.3
  flutter_launcher_icons: ^0.9.2
  firebase_core: ^1.11.0
  firebase_database: ^9.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"


flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"



  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

